"""
Enumerations for LinkedIn API models.

This module contains all the enumerations used in the LinkedIn API models.
These enums help standardize the values used in requests and responses.
"""

from enum import Enum, auto

class JobType(str, Enum):
    """Types of job positions."""
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    TEMPORARY = "TEMPORARY"
    VOLUNTEER = "VOLUNTEER"
    INTERNSHIP = "INTERNSHIP"
    APPRENTICESHIP = "APPRENTICESHIP"
    FREELANCE = "FREELANCE"
    OTHER = "OTHER"

class ExperienceLevel(str, Enum):
    """Experience levels for job positions."""
    INTERNSHIP = "INTERNSHIP"
    ENTRY_LEVEL = "ENTRY_LEVEL"
    ASSOCIATE = "ASSOCIATE"
    MID_SENIOR = "MID_SENIOR"
    DIRECTOR = "DIRECTOR"
    EXECUTIVE = "EXECUTIVE"

class LocationType(str, Enum):
    """Types of job locations."""
    REMOTE = "REMOTE"
    ON_SITE = "ON_SITE"
    HYBRID = "HYBRID"

class Industry(str, Enum):
    """Industry categories for companies and jobs."""
    TECHNOLOGY = "TECHNOLOGY"
    FINANCE = "FINANCE"
    HEALTHCARE = "HEALTHCARE"
    EDUCATION = "EDUCATION"
    MANUFACTURING = "MANUFACTURING"
    RETAIL = "RETAIL"
    CONSULTING = "CONSULTING"
    ENTERTAINMENT = "ENTERTAINMENT"
    MEDIA = "MEDIA"
    TELECOMMUNICATIONS = "TELECOMMUNICATIONS"
    TRANSPORTATION = "TRANSPORTATION"
    AEROSPACE = "AEROSPACE"
    AUTOMOTIVE = "AUTOMOTIVE"
    ENERGY = "ENERGY"
    PHARMACEUTICALS = "PHARMACEUTICALS"
    BIOTECHNOLOGY = "BIOTECHNOLOGY"
    CONSTRUCTION = "CONSTRUCTION"
    REAL_ESTATE = "REAL_ESTATE"
    HOSPITALITY = "HOSPITALITY"
    TRAVEL = "TRAVEL"
    GOVERNMENT = "GOVERNMENT"
    NONPROFIT = "NONPROFIT"
    OTHER = "OTHER"

class ConnectionDegree(int, Enum):
    """Degree of connection between LinkedIn users."""
    FIRST = 1
    SECOND = 2
    THIRD = 3
    OUT_OF_NETWORK = 4

class ProfileLanguage(str, Enum):
    """Supported languages for LinkedIn profiles."""
    ENGLISH = "en"
    SPANISH = "es"
    FRENCH = "fr"
    GERMAN = "de"
    ITALIAN = "it"
    PORTUGUESE = "pt"
    DUTCH = "nl"
    CHINESE = "zh"
    JAPANESE = "ja"
    KOREAN = "ko"
    RUSSIAN = "ru"
    NOVICE = "NOVICE"
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"
    EXPERT = "EXPERT"

class CompanySize(str, Enum):

    """Company size categories."""
    SELF_EMPLOYED = "SELF_EMPLOYED"
    ONE_TO_10_EMPLOYEES = "1-10_EMPLOYEES"
    ELEVEN_TO_50_EMPLOYEES = "11-50_EMPLOYEES"
    FIFTY_ONE_TO_200_EMPLOYEES = "51-200_EMPLOYEES"
    TWO_HUNDRED_ONE_TO_500_EMPLOYEES = "201-500_EMPLOYEES"
    FIVE_HUNDRED_ONE_TO_1000_EMPLOYEES = "501-1000_EMPLOYEES"
    ONE_THOUSAND_ONE_TO_5000_EMPLOYEES = "1001-5000_EMPLOYEES"
    FIVE_THOUSAND_ONE_TO_10000_EMPLOYEES = "5001-10000_EMPLOYEES"
    TEN_THOUSAND_OR_MORE_EMPLOYEES = "10001+_EMPLOYEES"

class CompanyType(str, Enum):
    """Types of company structures."""
    PUBLIC_COMPANY = "PUBLIC_COMPANY"
    PRIVATELY_HELD = "PRIVATELY_HELD"
    PARTNERSHIP = "PARTNERSHIP"
    PRIVATE_EQUITY = "PRIVATE_EQUITY"
    NON_PROFIT = "NON_PROFIT"
    SELF_EMPLOYED = "SELF_EMPLOYED"
    GOVERNMENT_AGENCY = "GOVERNMENT_AGENCY"
    SOLE_PROPRIETORSHIP = "SOLE_PROPRIETORSHIP"
    EDUCATIONAL_INSTITUTION = "EDUCATIONAL_INSTITUTION"

class JobFunction(str, Enum):
    """Job function categories."""
    ACCOUNTING = "ACCOUNTING"
    ADMINISTRATIVE = "ADMINISTRATIVE"
    ARTS_AND_DESIGN = "ARTS_AND_DESIGN"
    BUSINESS_DEVELOPMENT = "BUSINESS_DEVELOPMENT"
    COMMUNITY_AND_SOCIAL_SERVICES = "COMMUNITY_AND_SOCIAL_SERVICES"
    CONSULTING = "CONSULTING"
    EDUCATION = "EDUCATION"
    ENGINEERING = "ENGINEERING"
    ENTREPRENEURSHIP = "ENTREPRENEURSHIP"
    FINANCE = "FINANCE"
    HEALTHCARE_SERVICES = "HEALTHCARE_SERVICES"
    HUMAN_RESOURCES = "HUMAN_RESOURCES"
    INFORMATION_TECHNOLOGY = "INFORMATION_TECHNOLOGY"
    LEGAL = "LEGAL"
    MARKETING = "MARKETING"
    MEDIA_AND_COMMUNICATION = "MEDIA_AND_COMMUNICATION"
    MILITARY_AND_PROTECTIVE_SERVICES = "MILITARY_AND_PROTECTIVE_SERVICES"
    OPERATIONS = "OPERATIONS"
    PRODUCT_MANAGEMENT = "PRODUCT_MANAGEMENT"
    PROGRAM_AND_PROJECT_MANAGEMENT = "PROGRAM_AND_PROJECT_MANAGEMENT"
    PURCHASING = "PURCHASING"
    QUALITY_ASSURANCE = "QUALITY_ASSURANCE"
    REAL_ESTATE = "REAL_ESTATE"
    RESEARCH = "RESEARCH"
    SALES = "SALES"
    SUPPORT = "SUPPORT"

class SeniorityLevel(str, Enum):
    """Seniority levels for job positions."""
    INTERNSHIP = "INTERNSHIP"
    ENTRY_LEVEL = "ENTRY_LEVEL"
    ASSOCIATE = "ASSOCIATE"
    MID_SENIOR = "MID_SENIOR"
    DIRECTOR = "DIRECTOR"
    EXECUTIVE = "EXECUTIVE"
